name = "eryxon-flow"
compatibility_date = "2024-01-01"

[assets]
directory = "./website/dist"

[env.production]
name = "eryxon-flow"
vars = { NODE_VERSION = "20" }

[env.preview]
name = "eryxon-flow-preview"
